import "osl/ws"
import "osl/requests"
import "osl/fs"
import "osl/lock"

import "math/rand"

import "./messages.osl"
import "./handlers.osl"
import "./db.osl"

"*Server" server = nil

object users = {}
object userConnections = {}

def newConnection(*Connection conn) (
    log "New connection"
    conn.Send({
        "cmd": "handshake",
        "val": {
            server: {
                name: "DMs",
                icon: "https://originchats.mistium.com/dms.png",
                type: "direct",
                url: "wss://dms.mistium.com",
                owner: {
                    name: "Mist"
                }
            },
            limits: {
                post_content: 2000
            },
            version: "1.1.0",
            validator_key: "originChats-dms"
        }
    })
)

def handleMessage(*Connection conn, string message) (
  any rawMsg = message.JsonParse()

  if typeof(rawMsg) != "object" (
    return
  )
  object msg = rawMsg.assert(object)

  string listener = ""
  if typeof(msg.listener) == "string" (
    listener = msg.listener.toStr()
  )

  string cmd = msg.cmd.toStr()
  object response = null

  switch cmd (
  case "auth"
    response = handleAuth(conn, msg)
  case "channels_get"
    response = handleChannelsGet(conn, msg)
  case "users_list"
    response = handleUsersList(conn, msg)
  case "users_online"
    response = handleUsersOnline(conn, msg)
  case "messages_get"
    response = handleMessagesGet(conn, msg)
  case "message_new"
    response = handleMessageNew(conn, msg)
  case "message_edit"
    response = handleMessageEdit(conn, msg)
  case "message_delete"
    response = handleMessageDelete(conn, msg)
  case "message_react_add"
    response = handleMessageReactAdd(conn, msg)
  case "message_react_remove"
    response = handleMessageReactRemove(conn, msg)
  case "dm_create"
    response = handleDMCreate(conn, msg)
  case "typing"
    response = handleTyping(conn, msg)
  )

  if response == null (
    return
  )

  if listener != "" (
      response.listener = listener
    )

  if response.global.toBool() (
    string channel = response.channel.toStr()
    if channel != "" (
      sendMessageToAllUsersInChannel(conn, channel, response)
    )
    conn.Send(response)
    return
  )
  
  conn.Send(response)
)

def closeConnection(*Connection conn) (
    string id = getUserId(conn)
    string username = getUsername(conn)
    log "Connection closed for " ++ username
    users.delete(conn)
    if id != "" (
        userConnections.delete(id)
        broadcastUserDisconnect(id)
    )
)

def startPingTimer() (
    while true (
        wait 60
        server.Broadcast({
            cmd: "ping"
        }.JsonStringify())
    )
)

def main() (
    fs.Mkdir("db")
    fs.Mkdir("db/users")
    fs.Mkdir("db/channels")

    server = ws.NewServer(":5618", "/")

    server.OnConnect(newConnection)
    server.OnMessage(handleMessage)
    server.OnDisconnect(closeConnection)

    go startPingTimer()
    server.Start()
)